name: experimental
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animated_flip_counter: ^0.2.6
  fast_noise: ^2.0.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  google_fonts: ^6.1.0
  supabase_flutter: ^1.10.25

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  melos: ^3.3.0

flutter:
  uses-material-design: true
